### ISSUE TITLE
very slow parsing

### ISSUE THREAD

**Issue by yaron-shamul** [noxone/regex-generator#169]
first of all - very nice project!! 
would you consider get a files instead of reading a very long string? 
I had a problem where I put some very large text (like html)

**Comment by noxone** [comment]
Thank you @yaron-shamul 
But I don't understand the problem. Do you want to read a file and scan the whole file using the regex? So instead of hardcoding the string in the example you want to open a file?

**Comment by yaron-shamul** [comment]
I was having an issue to handle a very big html-file with your software. Try send your visualiser a very large amount of text to analyse.

**Comment by yaron-shamul** [comment]
In addition I want a feature that will also help- a files analysis:

Take a file or a files or an hierarchy of files and analyse the text in it in some sort of way

**Comment by noxone** [comment]
Ah, so if the input too big then the parsing is quite slow? 
This is fairly possible. Actually the page tries to parse a lot of regular expressions without knowing whether anything will work. And after that it tries to find some combinations. So I think the runtime might be something like O(2^n). And as this is something I can't change right now (because I'm just searching for patterns and pattern combinations) the only thing that comes to my mind:
Add a limit the input length.

**Comment by noxone** [comment]
The purpose of this project is not, to parse large files.

I don't know if there is a good and useful way to parse large files or even a set of larger files and automatically generate a regex from them. This project should help to find a first approach for a regex. The expressions generated will probably never be optimal (because the website does not know what you are trying to achieve), but hopefully they can provide a first starting point.

In my opinion, a large file, such as an HTML file, should not be parsed with a single regex. In my opinion, that is not possible in a reasonable way. Many smaller expressions are necessary here. For HTML files, I think it makes sense to write your own parser - or better: to use a ready-made one. Smaller areas of the HTML file (e.g. individual tags) can be recognised via a regex. In this case, however, a short excerpt from the file is sufficient as input for this project.

The larger and more complex the input, the more I see the need to use a "grammar" instead of a regex. For example, with [Xtext](https://www.eclipse.org/Xtext/) there is the possibility to develop a language with its own grammar. These basically use the same techniques as those used in a regex, but are much more flexible.

**Comment by yaron-shamul** [comment]
Alright got it, anyway thank you 🙂
