### ISSUE TITLE
url overflow css bug

### ISSUE THREAD

**Issue by ngochangjelly** [noxone/regex-generator#84]
**Describe the bug**
When I enter a long URL, the page is broken

**To Reproduce**
1. Go to 'https://regex-generator.olafneumann.org/'
2. On paste a text sample, enter: "https://shopee.vn/-M%C3%A3-WAMT1005-gi%E1%BA%A3m-10k-%C4%91%C6%A1n-0k-C%E1%BB%B0C-R%E1%BA%BA-D%C3%89P-%C4%90%E1%BA%BE-TR%E1%BA%A4U-NAM-N%E1%BB%AE-2-QUAI-BIRKEN-UNISEX-DA-PU-M%C3%80U-%C4%90EN-DETA21D-i.301144779.6149149324"
3. Scroll down to part 2 'Which parts of the text are interesting for you?'
4. See the error

**Expected behavior**
I don't know whether this is a bug or a feature, but I think it could be improved although I know this is not of priority

**Screenshots**
[image](https://i.imgur.com/GOcAn2E.png)

**Desktop (please complete the following information):**
 - OS:MacOS
 - Browser: Chrome

**Comment by lars-sh** [comment]
@noxone, this should be fixed once the line https://github.com/noxone/regex-generator/blob/master/regex-generator-web/src/main/resources/regex-generator.css#L19 is activated.

You disabled it with https://github.com/noxone/regex-generator/commit/5cdf06c5b6927b23330864feb237a4e537ca9f21, but I'm not sure why.

**Comment by noxone** [comment]
@lars-sh yes, I did that on purpose. Because:
When activating _that line_, the content of "Step 2" will be scrollable and the error does not occur any more. _But_ then the popups used to chose the patterns will also be clipped inside the same div. And at least on Windows you will see a scroll bar at the bottom of the div. (That scroll bar does not bother me, but anyhow, it's there)

The only solution I can currently think of is, that the popups need to displayed outside of the `rg-match-container` div and then somehow horizontally adjusted to the scroll value of that very div. Then the popups would even hover over the scroll bar. Do you have another idea?

**Comment by lars-sh** [comment]
@noxone, ah, I remember. What about activating _that line_ and modifying the `padding-bottom` of `#rg_result_container > .rg-match-container` based on the height and position of the popup? Then the scrollbar might move on hover, but that's might be a better situation than now.

**Comment by noxone** [comment]
Hm, yes, sizing the `.rg-match-container` based on the size of the popups sounds good.
We might need some kind of smooth transition between the different sizes. Otherwise it might happen that the page "flickers" a bit, while typing the text sample.

And if the free space under the match display is too big, we might need to find something to display so that users don't wonder why there is so much unused space.

**Comment by noxone** [comment]
@lars-sh I did some dirty jQuery stuff in Kotlin to roughly compute the height of the match presentation. It's not the best solution, yet. It needs some refactoring and the computation is still quite fuzzy. So I will optimize it.

Could you build something so the height changes smoothly?
